name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: echo "Deploying to test..."
      # Add your deployment command here
